samples: samples.tsv
units: units.tsv

# the sequencing adapter
adapter: "GATCGGAAGAGCACACGTCTGAACTCCAGTCACATCACGATCTCGTATGCCGTCTTCTGCTTG"

ref:
  transcriptome: "data/ref/Mus_musculus.GRCm38.cdna.all.plus_RUNX1a_GFP.fa"
  # species needs to be an identifier known to biomart, e.g. mmusculus for mmusculus_gene_ensembl
  species: mmusculus

pca:
  labels:
    # columns of sample sheet to use for PCA
    - RUNX1a
    - Dox


diffexp:
  # desired false discovery rate
  FDR: 0.2
  # model for sleuth differential expression analysis
  models:
    RUNX1a_only: 
      full: ~RUNX1a_plus_minus_Dox + donor_animal_first_passage
      reduced: ~donor_animal_first_passage
    RUNX1a_AND_Dox_vs_rest: 
      full: ~RUNX1a_AND_Dox + donor_animal_first_passage
      reduced: ~donor_animal_first_passage

params:
  kallisto: "-b 100"
  # these cutadapt parameters need to contain the required flag(s) for the type of adapter(s) to trim
  cutadapt-se: ""
  cutadapt-pe: "-g AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT -A GATCGGAAGAGCACACGTCTGAACTCCAGTCACATCACGATCTCGTATGCCGTCTTCTGCTTG -G AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT"
