samples: config/samples.tsv
units: config/units.tsv

resources:
  ref:
    transcriptome: "resources/ref/Mus_musculus.GRCm38.cdna.all.plus_RUNX1a_GFP.fa"
    # species needs to be an identifier known to biomart, e.g. mmusculus, hsapiens
    species: mmusculus
    # this is the version of the bioconda package `bioconductor-org.{species}`.eg.db` that
    # you want -- this needs to be compatible with the versions `r-base` and the
    # bioconductor packages specified e.g. in `envs/` files `fgsea.yaml`, `spia.yaml` and
    # `ens_gene_to_go.yaml`
    species_db_version: "3.10"
  ontology:
    # gene ontology to download, used e.g. in goatools
    gene_ontology: "http://current.geneontology.org/ontology/go-basic.obo"

pca:
  labels:
    # columns of sample sheet to use for PCA
    - RUNX1a
    - Dox

diffexp:
  # samples to exclude (e.g. outliers due to technical problems)
  exclude:
  # model for sleuth differential expression analysis
  models:
    RUNX1a_only: 
      full: ~RUNX1a_plus_minus_Dox + donor_animal_first_passage + library_prep
      reduced: ~donor_animal_first_passage + library_prep
      # Binary valued covariate that shall be used for fold change/effect size
      # based downstream analyses.
      primary_variable: RUNX1a_plus_minus_Dox
    RUNX1a_AND_Dox_vs_rest: 
      full: ~RUNX1a_AND_Dox + donor_animal_first_passage + library_prep
      reduced: ~donor_animal_first_passage + library_prep
      # Binary valued covariate that shall be used for fold change/effect size
      # based downstream analyses.
      primary_variable: RUNX1a_AND_Dox

enrichment:
  goatools:
    # tool is only run if set to `true`
    activate: true
    fdr_genes: 0.05
    fdr_go_terms: 0.05
  fgsea:
    # tool is only run if set to `true`
    activate: true
    # if activated, you need to provide a GMT file with gene sets of interest
    gene_sets_file: "resources/gene_sets/all_gene_sets.gmt"
    fdr_gene_set: 0.05
    nperm: 100000
  spia:
    # tool is only run if set to `true`
    activate: true
    # pathway database to use in SPIA, needs to be available for
    # the species specified by resources -> ref -> species above
    pathway_database: "reactome"

bootstrap_plots:
  # desired false discovery rate for bootstrap plots, i.e. a lower FDR will result in fewer boxplots generated
  FDR: 0.01
  # maximum number of bootstrap plots to generate, i.e. top n discoveries to plot
  top_n: 20
  color_by: condition
  # for now, this will plot the sleuth-normalised kallisto count estimations with kallisto
  # for all the transcripts of the respective genes
  genes_of_interest:
    - Mecom
    - Hlf
    - Cebpa
    - Gzmb
    - Egfl7
    - Gimap6
    - Gimap4

plot_vars:
  # significance level used for plot_vars() plots
  sig_level: 0.1

params:
  kallisto: "-b 100"
  # these cutadapt parameters need to contain the required flag(s) for the type of adapter(s) to trim
  cutadapt-se: ""
  cutadapt-pe: "-g AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT -A GATCGGAAGAGCACACGTCTGAACTCCAGTCACATCACGATCTCGTATGCCGTCTTCTGCTTG -G AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT --minimum-length 33 -e 0.005 --overlap 7"
